language: node_js

# Use container-based infrastructure
sudo: false

node_js:
  - "lts/boron"
  - "lts/carbon"
  - "stable"

script:
  - npm run lint
  - npm run test:cover

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: 9eac8d2b468e15ffa2109c1984945db4230ab94232c64064a9a658b17be43c14
